config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]
  get 'welcome' => 'pages#welcome'
  get 'aboutme' => 'about_me#aboutme'
  get 'projects' => 'projects#projects'
  root 'pages#welcome'

end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,		:validate => true
	attribute :email,		:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,		:validate => true
	attribute :nickname,	:captcha => true

	def headers 
		{
			:subject => "Contact Form",
			:to => "danny.stahl@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
	def aboutme
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def welcome
		
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def projects
	end
end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about_me/aboutme.html.erb
<main>
<div class="container">	
	<h1>About me</h1>
	<div class="col-sm-8 aboutme">
		<p>In this section you will learn who I am and some of the things I've accomplished.</p>

		<p>I grew up in the San Fernando Valley that's located north of downtown Los Angeles, CA. From a young age I've always tinkered with technology. I was that one in the family that could fix the TV, radio, and even set up the Bluetooth for the car. Once out of high school my main focus was music. I was a guitarist for my high-school band Halvmane, which means half-moon in Finnish. I was so involved with music I eventually got my audio engineering degree from MI in Hollywood, CA. As soon as I was out of school I interned at a studio and learned many techniques that I wasn't taught in school. Eventually the studio trusted me so much that they allowed me to record a few songs for my friend. I had an amazing experience their, but all good things must come to an end. In 2014 I decided to move on. I wasn't happy not making a living doing audio engineering gigs, so I made a career change. That same year I applied for the software engineering degree at ITT Tech in Sylmar, Ca. I knew once I was in that this was the right move for me. I knew a little HTML and CSS, but once I was introduced to JavaScript my whole world changed. Soon after graduation I learned the language Ruby and then Ruby on Rails.</p>

		<h4>Extra stuff not covered</h4>
		<ul>
			<li>Eagle Scout since 2006</li>
			<li>Ranger Scout since 2007</li>
			<li>Spanish is my 2nd language</li>
		</ul>
	</div>
</div>	
</main>

app/views/contacts/create.html.erb
<main>
	<div class="container">
		<h1>Thank you for your message!</h1>
		<p>I'll get back to you shortly.</p>
	</div>
</main>

app/views/contacts/new.html.erb
<main>
  <div class="container">
    <h1>Contact Form</h1>
    <p>Send me a message and I will get back to you shortly.</p>

    <%= form_for @contact do |f| %>
      <%= f.label :name%><br>
      <%= f.text_field :name, required: true %>

      <br>

      <%= f.label :emai%><br>
      <%= f.email_field :email, required: true %>

      <br>

      <%= f.label :message%><br>
      <%= f.text_area :message, as: :text %>

      <div class="hidden">
        <%= f.label :nickname%><br>
      <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>

      <%= f.submit 'Send Message', class: "btn" %>
    <% end -%>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<nav>
	    <div class="nav-wrapper container">
	    	<a class="brand-logo">Daniel Stahl</a>
	      	<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		    <ul class="right hide-on-med-and-down">
		    	<li><%= link_to 'Welcome'.html_safe, welcome_path %></li>
				<li><%= link_to 'About me'.html_safe, aboutme_path %></li>
				<li><%= link_to 'Projects'.html_safe, projects_path %></li>
				<!-- <li><%= link_to 'Blog'.html_safe, 'https://medium.com/@danielstahl' %></li> -->
				<li><%= link_to 'Contact'.html_safe, new_contact_path %></li>
				<li><%= link_to 'Twitter'.html_safe, 'https://twitter.com/LittleJazzHands', target: :_blank %></li>
				<li><%= link_to 'Github'.html_safe, 'https://github.com/daniel-stahl', target: :_blank %></li>
		    </ul>
		    <ul class="side-nav" id="mobile-demo">
		        <li><%= link_to 'Welcome'.html_safe, welcome_path %></li>
				<li><%= link_to 'About me'.html_safe, aboutme_path %></li>
				<li><%= link_to 'Projects'.html_safe, projects_path %></li>
				<!-- <li><%= link_to 'Blog'.html_safe, 'https://medium.com/@danielstahl', target: :_blank %></li> -->
				<li><%= link_to 'Contact'.html_safe, new_contact_path %></li>
				<li><%= link_to 'Twitter'.html_safe, 'https://twitter.com/LittleJazzHands', target: :_blank %></li>
				<li><%= link_to 'Github'.html_safe, 'https://github.com/daniel-stahl', target: :_blank %></li>
		    </ul>
	    </div>
  	</nav>

	<!-- <main> -->
		<%= yield %>
	<!-- </main> -->

	<footer class="page-footer">
		<p>Made with <i class="material-icons">favorite</i></p>
	</footer>	
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>	
</body>
</html>

app/views/pages/welcome.html.erb
<main class="bgimg">
	<div class="container">
		<div class="welcome-content">
			<h3>Coffee connoisseur and tech junky. I love following new start ups and developing Ruby on Rails web apps.</h3>
			<%= link_to "View my Work", 'projects', :class => "btn" %>
		</div>
	</div>
</main>	

app/views/projects/projects.html.erb
<main>
<div class="container">
<h1>Projects</h1>
	<div class="row">
		<div class="col-sm-6 col-md-4">
  		<div class="thumbnail">
    			<%=image_tag("clover.png", alt: "Clover Podcast")%>
    			<div class="caption">
      			<h3>Clover Podcast</h3>
      			<p>Discover your new favorite podcast, or create your own.</p>
      			<a href="https://cloverpodcast.herokuapp.com/" target="_blank" class="btn btn-default" role="button">Visit</a>
    			</div>
  		</div>
    </div>
	</div>
</div>  
</main>